import test from 'node:test';import assert from 'node:assert/strict';import {evaluate} from '../src/index.js';import {spawnSync} from 'node:child_process';import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
const config={version:1,rules:[{label:'prod',env:{NODE_ENV:'production'}}]};
test('blocks exact configured production, permits development',()=>{assert.equal(evaluate(config,{env:{NODE_ENV:'production'}}).allowed,false);assert.equal(evaluate(config,{env:{NODE_ENV:'development'}}).allowed,true);});
test('missing env fails closed',()=>{assert.throws(()=>evaluate(config,{env:{}}),/missing/);assert.throws(()=>evaluate(config,{env:{NODE_ENV:''}}));});
test('override must match exact phrase, only matched labels',()=>{assert.equal(evaluate(config,{env:{NODE_ENV:'production'},override:'yes'}).allowed,false);assert.equal(evaluate(config,{env:{NODE_ENV:'production'},override:'I UNDERSTAND prod'}).allowed,true);});
test('AND within rule, OR across rules; exact host names',()=>{const c={version:1,rules:[{label:'primary',env:{NODE_ENV:'production'},hosts:['db-prod']},{label:'other',hosts:['other-prod']}]};assert.equal(evaluate(c,{env:{NODE_ENV:'production'},host:'local'}).allowed,true);assert.deepEqual(evaluate(c,{env:{NODE_ENV:'production'},host:'db-prod'}).matchedRules,['primary']);assert.equal(evaluate(c,{env:{NODE_ENV:'development'},host:'other-prod'}).allowed,false);});
test('no regex/substrings or secret values in result',()=>{const c={version:1,rules:[{label:'db',env:{DB_HOST:'prod.internal'}}]};assert.equal(evaluate(c,{env:{DB_HOST:'not-prod.internal'}}).allowed,true);assert.ok(!JSON.stringify(evaluate(c,{env:{DB_HOST:'prod.internal'}})).includes('prod.internal'));});
test('malformed configs rejected even on nonmatching rule',()=>{for(const c of [{},{version:2,rules:[]},{version:1,rules:[]},{version:1,rules:[{label:'x'}]},{version:1,rules:[{label:'x',env:{}}]},{version:1,rules:[{label:'x',hosts:['*prod*']}]},{version:1,rules:[{label:'x\n',hosts:['prod']}]},{version:1,rules:[{label:'x',hosts:['prod']},{label:'x',hosts:['prod']}]}])assert.throws(()=>evaluate(c,{env:{NODE_ENV:'dev'},host:'local'}));});
test('CLI only evaluates, exit codes fail closed',()=>{const dir=mkdtempSync(join(tmpdir(),'guard-'));try{const path=join(dir,'guard.json');writeFileSync(path,JSON.stringify(config));let x=spawnSync(process.execPath,['src/cli.js','--config',path,'--json'],{env:{...process.env,NODE_ENV:'production'},encoding:'utf8'});assert.equal(x.status,2);assert.equal(JSON.parse(x.stdout).allowed,false);x=spawnSync(process.execPath,['src/cli.js','--config',path,'--override','I UNDERSTAND prod'],{env:{...process.env,NODE_ENV:'production'},encoding:'utf8'});assert.equal(x.status,0);x=spawnSync(process.execPath,['src/cli.js','--config',path,'--','echo','hi'],{encoding:'utf8'});assert.equal(x.status,1);}finally{rmSync(dir,{recursive:true,force:true});}});
